### ISSUE TITLE
global properties settings are not recreated correctly when reloading an awd

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#181]
**Steps to reproduce**
- open a new awd file
- create a sphere geometry and add it as a mesh
- goto the global properties panel and uncheck "embed textures", "include normal data", "include tangent data"
- adjust the compression setting from deflate to lzma
- adjust the user attributes namespace to http://example.com/mynewns
- save the file
- reload the file

**expected result**

The global options are recreated as saved

**actual result**

The global options reset to their defaults

**Comment by 80prozent** [comment]
Hi
I think this isnt fixed very easy. 
I see 2 problems: 
- away3d needs to support the different options (something like GlobalExportSettings-class) and a Event (something like GlobalExportSettingsComplete). This stuff needs to be added to Away3d engine, but is only used by AwayBuilder. 
- the options should only reload from a file, if its "opened", not "imported" ? (otherwise a import would overwrite settings the user might allready have set). ATM there is no way for the AWD2parser to know, if the awd-file that is parsed, is loaded by a "open", or a "import" command. Again, i think the AWD2Parser of Away3d would need a update (to know if it is "opening" or "importing" a file), but this update would only be usefull for AwayBuilder. 

Maybe this is a good time, to think about having a dedicated AWD2Parser for AwayBuilder, so we can make it work better for AwayBuilder, while not adding unneccassary stuff to the Away3d-engine.

**Comment by Jeronimoo** [comment]
Why not store this data into a project specific file ? An XML will do. This way the AWD would not be cluttered with data that is technically useless to anything but AwayBuilder.

You could also use the same AWD with different global properties depending on your target (e.g. Flash on the web vs mobile Air), all you'd need would be a new project file rather than a separate AWD which would be cumbersome to keep in sync with the original.

**Comment by 80prozent** [comment]
Hi Jeronimoo
Most of the Global-properties are not useless to anything but AwayBuilder.....
How would any parser read the file properly, if the file does not preserve the info, needed for parsing it (storage-precision / compression). 
Most of these data is stored as bitFlags in 2 byte of the AWD-FileHeader, so its really not that much of data. 

Thats beeing said, i think having a sepperate project-file for AwayBuilder could definitv make sense in the future, but for the feature-set thats available for awayBuilder right now, i think the AWD Format is quite sufficiant.
The Global Properties are for the FileSettings for the AWD. I think in future Versions, the AwayBuilder might have a sepperate Preferences-panel. The Settings in this Preferences-panel would be Settings that are only concerning AwayBuilder, and not the AWD it Outputs. So maybe for this Preferences we will need to add a sepperate Project-File.

**Comment by Jeronimoo** [comment]
Sounds good to me !
