### ISSUE TITLE
Animation does not work

### ISSUE THREAD

**Issue by 62316e** [awaytools/AwayBuilder#226]
"Skeleton is missing"

**Comment by 80prozent** [comment]
_Issue does not work_

"Information is missing"

:)

what are you trying to do ?

Import a SkeletonAnimation into AwayBuilder and set up a Animator for the imported animation ?

or is the SkeletonAnimation allready set up in AwayBuilder, and you are trying to save and reload it ?

If you give some more information, we can help you more easily...

**Comment by 62316e** [comment]
Sorry,
I created a character in 3ds max with custom Skeleton.
Then i exported it into AWD format (checked the export animation).

The question is how to see that animation in AwayBuilder?
Works well in Alternativa3D Player with A3D format.

btw, i dont remember where i get that 3DS Max Plugin, can you please point me to the latest version?

**Comment by 80prozent** [comment]
ok...
after import you see "Skeleton" and one or multiple "AnimationNodes" in the Animations-Panel ?
if yes: you have to create a new "SkeletonAnimationSet", and add one ore more of your AnimationNodes to it.
You can add the Animation-Nodes by dragging them onto the AnimationSet, so they get childs of the AnimationSet (atm you need to do this in the animation-panel, because dragging the animations from the animations-panel into the Animation-Nodes-list of the AnimationSet-properties-panel does not seam to work) 
if you have assignt some animationNodes, create a Animator (do this in the AnimationSet-properties-panel)
now you should be able to assign the animator to meshes.

You can open the geometry-properties-panel, of the geometry you want to animate, and open one of its subGeometries. now you can check the type of the subGeometry. to be able to be animated by a SkeletonAnimator, the subGeometries all must be of type "SkinnedSubGeometry". 

A SkeletonAnimationSet has a property called "jointsperVertex", which defines how many joints are used to deform a vert of the mesh. The SkinnedSubGeometry provides the binding-data, which should correspond to this "JointsPerVertex" (e.g. you can not assign a SkeletonAnimationSet with a "JointsPerVertex" of 3 to a SkinnedSubGeometry, that only provides 2 weights-values per vert....).

if you like, you can send your exported AWD, to 80prozent[a]differentdesign.de and i can tell you if its working for me....

i am no 3dsMax user myself, and there had be no one updating the 3dsmax-plugin for some time...
the 3dsmax-exporter is the only AWD_Extension, that is written in pure c++ instead of python. 
atm i am working on the python-library and the python exporters for maya/c4d/blender. 
we have found someone thats willing and able to work on the 3dsMax-plugin (https://github.com/persanker) , but i dont know if he has compiled a new version yet. If so, i think the releases will appear in the release section of the 3ds-max-extensions...
https://github.com/awaytools/AwayExtensions-3dsmax/releases

maybe you can get in contact with percy and help him by testing / providing test-scenes / etc ?  
I still havnt even had a chance to install 3dsMax and check it out myself...(and since i am no 3dsmax-user checking it out for me means: learning 3dsmax...)

cheers 
Robin

**Comment by 62316e** [comment]
I've send you an email.
I dont see any animation nodes or sets in away builder.

**Comment by 80prozent** [comment]
3dsmax exporter has been refactored and updated. Compiled Versions of the plugin and documentation will be available soon. 
Animation (Skeleton + vertex) should be working.
