### ISSUE TITLE
Does not remember load compression settings. 

### ISSUE THREAD

**Issue by karimbeyrouti** [awaytools/AwayBuilder#233]
ISSUE / DESCRIPTION: 
If an AWD with UNCOMPRESSED is opened - the compression setting defaults back to DEFLATE 

EXPECTED BEHAVIOUR:
An AWD that is UNCOMPRESSED should show up as being UNCOMPRESSED in the settings - and save with the same setting it was opened with .

**Comment by 80prozent** [comment]
Hi karim

i just tested, and for me its like that:
- open AWD-File using "File"-menu: compression-setting gets loaded = ok
- open AWD-File by DragnDrop (selecting "No, create new library"): compression-setting gets loaded = ok
- when importing a file ("File"-menu / DragnDrap (and add to current library)): compression-setting does not get loaded = i think expected behaviour
- opening a AWD-File with AB (opening AB by doubleclicking the file): compression-setting does not get loaded = not ok / bug 

assigning it to me

**Comment by karimbeyrouti** [comment]
Hello ! That is indeed the bug / behaviour I am experiencing. Thank you .

**Comment by 80prozent** [comment]
Should be fixed in this commit:
https://github.com/awaytools/AwayBuilder/commit/224d33b10d9669124e634ce08012f444ce0afaf1
